<?php

/**
 * This is the model base class for the table "resultado_cuestionario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ResultadoCuestionario".
 *
 * Columns in table "resultado_cuestionario" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_cuestionario
 * @property integer $id_unidad_negocio
 * @property string $arreglo_id_preguntas_especificas
 * @property string $arreglo_respuestas_preguntas_especificas
 * @property string $arreglo_nombre_grupos_preguntas
 * @property string $arreglo_valores_posibles_preguntas
 * @property string $arreglo_valores_obtenidos
 *
 */
abstract class BaseResultadoCuestionario extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'resultado_cuestionario';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ResultadoCuestionario|ResultadoCuestionarios', $n);
	}

	public static function representingColumn() {
		return 'arreglo_nombre_grupos_preguntas';
	}

	public function rules() {
		return array(
			array('id_cuestionario, id_unidad_negocio', 'numerical', 'integerOnly'=>true),
			array('arreglo_id_preguntas_especificas, arreglo_respuestas_preguntas_especificas, arreglo_nombre_grupos_preguntas, arreglo_valores_posibles_preguntas, arreglo_valores_obtenidos', 'safe'),
			array('id_cuestionario, id_unidad_negocio, arreglo_id_preguntas_especificas, arreglo_respuestas_preguntas_especificas, arreglo_nombre_grupos_preguntas, arreglo_valores_posibles_preguntas, arreglo_valores_obtenidos', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_cuestionario, id_unidad_negocio, arreglo_id_preguntas_especificas, arreglo_respuestas_preguntas_especificas, arreglo_nombre_grupos_preguntas, arreglo_valores_posibles_preguntas, arreglo_valores_obtenidos', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_cuestionario' => Yii::t('app', 'Id Cuestionario'),
			'id_unidad_negocio' => Yii::t('app', 'Id Unidad Negocio'),
			'arreglo_id_preguntas_especificas' => Yii::t('app', 'Arreglo Id Preguntas Especificas'),
			'arreglo_respuestas_preguntas_especificas' => Yii::t('app', 'Arreglo Respuestas Preguntas Especificas'),
			'arreglo_nombre_grupos_preguntas' => Yii::t('app', 'Arreglo Nombre Grupos Preguntas'),
			'arreglo_valores_posibles_preguntas' => Yii::t('app', 'Arreglo Valores Posibles Preguntas'),
			'arreglo_valores_obtenidos' => Yii::t('app', 'Arreglo Valores Obtenidos'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;
		$criteria->compare('id_cuestionario', $this->id_cuestionario);
		$criteria->compare('id_unidad_negocio', $this->id_unidad_negocio);
		$criteria->compare('arreglo_id_preguntas_especificas', $this->arreglo_id_preguntas_especificas, true);
		$criteria->compare('arreglo_respuestas_preguntas_especificas', $this->arreglo_respuestas_preguntas_especificas, true);
		$criteria->compare('arreglo_nombre_grupos_preguntas', $this->arreglo_nombre_grupos_preguntas, true);
		$criteria->compare('arreglo_valores_posibles_preguntas', $this->arreglo_valores_posibles_preguntas, true);
		$criteria->compare('arreglo_valores_obtenidos', $this->arreglo_valores_obtenidos, true);
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}