<?php

/**
 * This is the model base class for the table "cuestionario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Cuestionario".
 *
 * Columns in table "cuestionario" available as properties of the model,
 * followed by relations of table "cuestionario" available as properties of the model.
 *
 * @property integer $id_cuestionario
 * @property string $nombre
 * @property string $descripcion
 *
 * @property GrupoPreguntas[] $grupoPreguntases
 */
abstract class BaseCuestionario extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cuestionario';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Cuestionario|Cuestionarios', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre', 'required'),
			array('nombre, descripcion', 'length', 'max'=>255),
			array('descripcion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_cuestionario, nombre, descripcion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'grupoPreguntases' => array(self::HAS_MANY, 'GrupoPreguntas', 'id_cuestionario'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_cuestionario' => Yii::t('app', 'Id Cuestionario'),
			'nombre' => Yii::t('app', 'Nombre'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'grupoPreguntases' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_cuestionario', $this->id_cuestionario);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('descripcion', $this->descripcion, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}