<?php

/**
 * This is the model base class for the table "proceso".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Proceso".
 *
 * Columns in table "proceso" available as properties of the model,
 * followed by relations of table "proceso" available as properties of the model.
 *
 * @property integer $id_proceso
 * @property string $nombre
 * @property string $descripcion
 * @property integer $id_macroproceso
 *
 * @property Riesgo[] $riesgos
 * @property Macroproceso $idMacroproceso
 * @property UnidadNegocio[] $unidadNegocios
 */
abstract class BaseProceso extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'proceso';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Proceso|Procesos', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre, id_macroproceso', 'required'),
			array('id_macroproceso', 'numerical', 'integerOnly'=>true),
			array('nombre, descripcion', 'length', 'max'=>255),
			array('descripcion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_proceso, nombre, descripcion, id_macroproceso', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'riesgos' => array(self::MANY_MANY, 'Riesgo', 'proceso_riesgo(id_proceso, id_riesgo)'),
			'idMacroproceso' => array(self::BELONGS_TO, 'Macroproceso', 'id_macroproceso'),
			'unidadNegocios' => array(self::MANY_MANY, 'UnidadNegocio', 'unidad_negocio_proceso(id_proceso, id_unidad_negocio)'),
		);
	}

	public function pivotModels() {
		return array(
			'riesgos' => 'ProcesoRiesgo',
			'unidadNegocios' => 'UnidadNegocioProceso',
		);
	}

	public function attributeLabels() {
		return array(
			'id_proceso' => Yii::t('app', 'Id Proceso'),
			'nombre' => Yii::t('app', 'Nombre'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'id_macroproceso' => null,
			'riesgos' => null,
			'idMacroproceso' => null,
			'unidadNegocios' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_proceso', $this->id_proceso);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('id_macroproceso', $this->id_macroproceso);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}