<?php

/**
 * This is the model base class for the table "tipo_causa".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TipoCausa".
 *
 * Columns in table "tipo_causa" available as properties of the model,
 * followed by relations of table "tipo_causa" available as properties of the model.
 *
 * @property integer $id_tipo_causa
 * @property string $nombre
 *
 * @property Causa[] $causas
 */
abstract class BaseTipoCausa extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tipo_causa';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TipoCausa|TipoCausas', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre', 'required'),
			array('nombre', 'length', 'max'=>255),
			array('id_tipo_causa, nombre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'causas' => array(self::HAS_MANY, 'Causa', 'id_tipo_causa'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_tipo_causa' => Yii::t('app', 'Id Tipo Causa'),
			'nombre' => Yii::t('app', 'Nombre'),
			'causas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_tipo_causa', $this->id_tipo_causa);
		$criteria->compare('nombre', $this->nombre, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}