<?php

/**
 * This is the model base class for the table "causa".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Causa".
 *
 * Columns in table "causa" available as properties of the model,
 * followed by relations of table "causa" available as properties of the model.
 *
 * @property integer $id_causa
 * @property string $nombre
 * @property integer $id_tipo_causa
 *
 * @property Riesgo[] $riesgos
 * @property TipoCausa $idTipoCausa
 */
abstract class BaseCausa extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'causa';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Causa|Causas', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre, id_tipo_causa', 'required'),
			array('id_tipo_causa', 'numerical', 'integerOnly'=>true),
			array('nombre', 'length', 'max'=>255),
			array('id_causa, nombre, id_tipo_causa', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'riesgos' => array(self::MANY_MANY, 'Riesgo', 'causa_riesgo(id_causa, id_riesgo)'),
			'idTipoCausa' => array(self::BELONGS_TO, 'TipoCausa', 'id_tipo_causa'),
		);
	}

	public function pivotModels() {
		return array(
			'riesgos' => 'CausaRiesgo',
		);
	}

	public function attributeLabels() {
		return array(
			'id_causa' => Yii::t('app', 'Id Causa'),
			'nombre' => Yii::t('app', 'Nombre'),
			'id_tipo_causa' => null,
			'riesgos' => null,
			'idTipoCausa' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_causa', $this->id_causa);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('id_tipo_causa', $this->id_tipo_causa);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}