<?php

/**
 * This is the model base class for the table "tipo_accion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TipoAccion".
 *
 * Columns in table "tipo_accion" available as properties of the model,
 * followed by relations of table "tipo_accion" available as properties of the model.
 *
 * @property integer $id_tipo_accion
 * @property string $nombre
 *
 * @property Riesgo[] $riesgos
 */
abstract class BaseTipoAccion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tipo_accion';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TipoAccion|TipoAccions', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre', 'required'),
			array('nombre', 'length', 'max'=>255),
			array('id_tipo_accion, nombre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'riesgos' => array(self::HAS_MANY, 'Riesgo', 'id_tipo_accion'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_tipo_accion' => Yii::t('app', 'Id Tipo Accion'),
			'nombre' => Yii::t('app', 'Nombre'),
			'riesgos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_tipo_accion', $this->id_tipo_accion);
		$criteria->compare('nombre', $this->nombre, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}