<?php

/**
 * This is the model base class for the table "actividad_control".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ActividadControl".
 *
 * Columns in table "actividad_control" available as properties of the model,
 * followed by relations of table "actividad_control" available as properties of the model.
 *
 * @property integer $id_actividad_control
 * @property string $nombre
 *
 * @property Riesgo[] $riesgos
 */
abstract class BaseActividadControl extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'actividad_control';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ActividadControl|ActividadControls', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre', 'required'),
			array('nombre', 'length', 'max'=>255),
			array('id_actividad_control, nombre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'riesgos' => array(self::HAS_MANY, 'Riesgo', 'id_actividad_control'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_actividad_control' => Yii::t('app', 'Id Actividad Control'),
			'nombre' => Yii::t('app', 'Nombre'),
			'riesgos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_actividad_control', $this->id_actividad_control);
		$criteria->compare('nombre', $this->nombre, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}