<?php

/**
 * This is the model base class for the table "riesgo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Riesgo".
 *
 * Columns in table "riesgo" available as properties of the model,
 * followed by relations of table "riesgo" available as properties of the model.
 *
 * @property integer $id_riesgo
 * @property string $codigo
 * @property integer $id_tipo_riesgo
 * @property integer $id_tipo_perdida
 * @property string $descripcion_causa
 * @property integer $id_actividad_control
 * @property string $descripcion_actividad_control
 * @property string $impacto_pesimista
 * @property string $impacto_probable
 * @property string $impacto_optimista
 * @property string $probabilidad_pesimista
 * @property string $probabilidad_probable
 * @property string $probabilidad_optimista
 * @property string $descripcion_impacto_pesimista
 * @property string $descripcion_impacto_probable
 * @property string $descripcion_impacto_optimista
 * @property string $descripcion_probabilidad_pesimista
 * @property string $descripcion_probabilidad_probable
 * @property string $descripcion_probabilidad_optimista
 * @property integer $id_tipo_accion
 * @property string $accion
 * @property double $impacto_deterministico
 * @property double $probabilidad_deterministica
 * @property double $riesgo_deterministico
 * @property double $impacto_estocastico
 * @property double $probabilidad_estocastica
 * @property double $riesgo_estocastico
 * @property string $indicador_riesgo
 * @property integer $id_grupo_riesgo
 * @property string $impacto_cualitativo
 * @property string $probabilidad_cualitativa
 * @property string $riesgo_cualitativo
 * @property integer $estado
 * @property string $nombre
 * @property double $desviacion_estandar
 *
 * @property Proceso[] $procesos
 * @property TipoRiesgo $idTipoRiesgo
 * @property TipoAccion $idTipoAccion
 * @property TipoPerdida $idTipoPerdida
 * @property ActividadControl $idActividadControl
 * @property GrupoRiesgo $idGrupoRiesgo
 * @property Causa[] $causas
 * @property ObjetivoEstrategico[] $objetivoEstrategicos
 * @property UnidadNegocio[] $unidadNegocios
 */
abstract class BaseRiesgo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'riesgo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Riesgo|Riesgos', $n);
	}

	public static function representingColumn() {
		return 'descripcion_causa';
	}

	public function rules() {
		return array(
			array('id_tipo_riesgo, id_tipo_perdida, descripcion_causa, id_actividad_control, descripcion_actividad_control, impacto_pesimista, impacto_probable, impacto_optimista, probabilidad_pesimista, probabilidad_probable, probabilidad_optimista, id_grupo_riesgo, nombre', 'required'),
			array('id_tipo_riesgo, id_tipo_perdida, id_actividad_control, id_tipo_accion, id_grupo_riesgo, estado', 'numerical', 'integerOnly'=>true),
			array('impacto_deterministico, probabilidad_deterministica, riesgo_deterministico, impacto_estocastico, probabilidad_estocastica, riesgo_estocastico, desviacion_estandar', 'numerical'),
			array('codigo, accion, indicador_riesgo, nombre', 'length', 'max'=>255),
			array('impacto_cualitativo, probabilidad_cualitativa, riesgo_cualitativo', 'length', 'max'=>20),
			array('descripcion_impacto_pesimista, descripcion_impacto_probable, descripcion_impacto_optimista, descripcion_probabilidad_pesimista, descripcion_probabilidad_probable, descripcion_probabilidad_optimista', 'safe'),
			array('codigo, descripcion_impacto_pesimista, descripcion_impacto_probable, descripcion_impacto_optimista, descripcion_probabilidad_pesimista, descripcion_probabilidad_probable, descripcion_probabilidad_optimista, id_tipo_accion, accion, impacto_deterministico, probabilidad_deterministica, riesgo_deterministico, impacto_estocastico, probabilidad_estocastica, riesgo_estocastico, indicador_riesgo, impacto_cualitativo, probabilidad_cualitativa, riesgo_cualitativo, estado, desviacion_estandar', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_riesgo, codigo, id_tipo_riesgo, id_tipo_perdida, descripcion_causa, id_actividad_control, descripcion_actividad_control, impacto_pesimista, impacto_probable, impacto_optimista, probabilidad_pesimista, probabilidad_probable, probabilidad_optimista, descripcion_impacto_pesimista, descripcion_impacto_probable, descripcion_impacto_optimista, descripcion_probabilidad_pesimista, descripcion_probabilidad_probable, descripcion_probabilidad_optimista, id_tipo_accion, accion, impacto_deterministico, probabilidad_deterministica, riesgo_deterministico, impacto_estocastico, probabilidad_estocastica, riesgo_estocastico, indicador_riesgo, id_grupo_riesgo, impacto_cualitativo, probabilidad_cualitativa, riesgo_cualitativo, estado, nombre, desviacion_estandar', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'procesos' => array(self::MANY_MANY, 'Proceso', 'proceso_riesgo(id_riesgo, id_proceso)'),
			'idTipoRiesgo' => array(self::BELONGS_TO, 'TipoRiesgo', 'id_tipo_riesgo'),
			'idTipoAccion' => array(self::BELONGS_TO, 'TipoAccion', 'id_tipo_accion'),
			'idTipoPerdida' => array(self::BELONGS_TO, 'TipoPerdida', 'id_tipo_perdida'),
			'idActividadControl' => array(self::BELONGS_TO, 'ActividadControl', 'id_actividad_control'),
			'idGrupoRiesgo' => array(self::BELONGS_TO, 'GrupoRiesgo', 'id_grupo_riesgo'),
			'causas' => array(self::MANY_MANY, 'Causa', 'causa_riesgo(id_riesgo, id_causa)'),
			'objetivoEstrategicos' => array(self::MANY_MANY, 'ObjetivoEstrategico', 'objetivo_estrategico_riesgo(id_riesgo, id_objetivo_estrategico)'),
			'unidadNegocios' => array(self::MANY_MANY, 'UnidadNegocio', 'riesgo_unidad_negocio(id_riesgo, id_unidad_negocio)'),
		);
	}

	public function pivotModels() {
		return array(
			'procesos' => 'ProcesoRiesgo',
			'causas' => 'CausaRiesgo',
			'objetivoEstrategicos' => 'ObjetivoEstrategicoRiesgo',
			'unidadNegocios' => 'RiesgoUnidadNegocio',
		);
	}

	public function attributeLabels() {
		return array(
			'id_riesgo' => Yii::t('app', 'Id Riesgo'),
			'codigo' => Yii::t('app', 'Codigo'),
			'id_tipo_riesgo' => null,
			'id_tipo_perdida' => null,
			'descripcion_causa' => Yii::t('app', 'Descripcion Causa'),
			'id_actividad_control' => null,
			'descripcion_actividad_control' => Yii::t('app', 'Descripcion Actividad Control'),
			'impacto_pesimista' => Yii::t('app', 'Impacto Pesimista'),
			'impacto_probable' => Yii::t('app', 'Impacto Probable'),
			'impacto_optimista' => Yii::t('app', 'Impacto Optimista'),
			'probabilidad_pesimista' => Yii::t('app', 'Probabilidad Pesimista'),
			'probabilidad_probable' => Yii::t('app', 'Probabilidad Probable'),
			'probabilidad_optimista' => Yii::t('app', 'Probabilidad Optimista'),
			'descripcion_impacto_pesimista' => Yii::t('app', 'Descripcion Impacto Pesimista'),
			'descripcion_impacto_probable' => Yii::t('app', 'Descripcion Impacto Probable'),
			'descripcion_impacto_optimista' => Yii::t('app', 'Descripcion Impacto Optimista'),
			'descripcion_probabilidad_pesimista' => Yii::t('app', 'Descripcion Probabilidad Pesimista'),
			'descripcion_probabilidad_probable' => Yii::t('app', 'Descripcion Probabilidad Probable'),
			'descripcion_probabilidad_optimista' => Yii::t('app', 'Descripcion Probabilidad Optimista'),
			'id_tipo_accion' => null,
			'accion' => Yii::t('app', 'Accion'),
			'impacto_deterministico' => Yii::t('app', 'Impacto Deterministico'),
			'probabilidad_deterministica' => Yii::t('app', 'Probabilidad Deterministica'),
			'riesgo_deterministico' => Yii::t('app', 'Riesgo Deterministico'),
			'impacto_estocastico' => Yii::t('app', 'Impacto Estocastico'),
			'probabilidad_estocastica' => Yii::t('app', 'Probabilidad Estocastica'),
			'riesgo_estocastico' => Yii::t('app', 'Riesgo Estocastico'),
			'indicador_riesgo' => Yii::t('app', 'Indicador Riesgo'),
			'id_grupo_riesgo' => null,
			'impacto_cualitativo' => Yii::t('app', 'Impacto Cualitativo'),
			'probabilidad_cualitativa' => Yii::t('app', 'Probabilidad Cualitativa'),
			'riesgo_cualitativo' => Yii::t('app', 'Riesgo Cualitativo'),
			'estado' => Yii::t('app', 'Estado'),
			'nombre' => Yii::t('app', 'Nombre'),
			'desviacion_estandar' => Yii::t('app', 'Desviacion Estandar'),
			'procesos' => null,
			'idTipoRiesgo' => null,
			'idTipoAccion' => null,
			'idTipoPerdida' => null,
			'idActividadControl' => null,
			'idGrupoRiesgo' => null,
			'causas' => null,
			'objetivoEstrategicos' => null,
			'unidadNegocios' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;
		$criteria->compare('id_riesgo', $this->id_riesgo);
		$criteria->compare('codigo', $this->codigo, true);
		$criteria->compare('id_tipo_riesgo', $this->id_tipo_riesgo);
		$criteria->compare('id_tipo_perdida', $this->id_tipo_perdida);
		$criteria->compare('descripcion_causa', $this->descripcion_causa, true);
		$criteria->compare('id_actividad_control', $this->id_actividad_control);
		$criteria->compare('descripcion_actividad_control', $this->descripcion_actividad_control, true);
		$criteria->compare('impacto_pesimista', $this->impacto_pesimista, true);
		$criteria->compare('impacto_probable', $this->impacto_probable, true);
		$criteria->compare('impacto_optimista', $this->impacto_optimista, true);
		$criteria->compare('probabilidad_pesimista', $this->probabilidad_pesimista, true);
		$criteria->compare('probabilidad_probable', $this->probabilidad_probable, true);
		$criteria->compare('probabilidad_optimista', $this->probabilidad_optimista, true);
		$criteria->compare('descripcion_impacto_pesimista', $this->descripcion_impacto_pesimista, true);
		$criteria->compare('descripcion_impacto_probable', $this->descripcion_impacto_probable, true);
		$criteria->compare('descripcion_impacto_optimista', $this->descripcion_impacto_optimista, true);
		$criteria->compare('descripcion_probabilidad_pesimista', $this->descripcion_probabilidad_pesimista, true);
		$criteria->compare('descripcion_probabilidad_probable', $this->descripcion_probabilidad_probable, true);
		$criteria->compare('descripcion_probabilidad_optimista', $this->descripcion_probabilidad_optimista, true);
		$criteria->compare('id_tipo_accion', $this->id_tipo_accion);
		$criteria->compare('accion', $this->accion, true);
		$criteria->compare('impacto_deterministico', $this->impacto_deterministico);
		$criteria->compare('probabilidad_deterministica', $this->probabilidad_deterministica);
		$criteria->compare('riesgo_deterministico', $this->riesgo_deterministico);
		$criteria->compare('impacto_estocastico', $this->impacto_estocastico);
		$criteria->compare('probabilidad_estocastica', $this->probabilidad_estocastica);
		$criteria->compare('riesgo_estocastico', $this->riesgo_estocastico);
		$criteria->compare('indicador_riesgo', $this->indicador_riesgo, true);
		$criteria->compare('id_grupo_riesgo', $this->id_grupo_riesgo);
		$criteria->compare('impacto_cualitativo', $this->impacto_cualitativo, true);
		$criteria->compare('probabilidad_cualitativa', $this->probabilidad_cualitativa, true);
		$criteria->compare('riesgo_cualitativo', $this->riesgo_cualitativo, true);
		$criteria->compare('estado', $this->estado);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('desviacion_estandar', $this->desviacion_estandar);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}