<?php

/**
 * This is the model base class for the table "unidad_negocio".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UnidadNegocio".
 *
 * Columns in table "unidad_negocio" available as properties of the model,
 * followed by relations of table "unidad_negocio" available as properties of the model.
 *
 * @property integer $id_unidad_negocio
 * @property string $nombre
 * @property string $descripcion
 * @property integer $id_empresa
 * @property integer $evaluacion
 *

 * @property Macroproceso[] $macroprocesos
 * @property Empresa $idEmpresa
 * @property Riesgo[] $riesgos
 * @property Cuestionario[] $cuestionarios
 */
abstract class BaseUnidadNegocio extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'unidad_negocio';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UnidadNegocio|UnidadNegocios', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre, id_empresa', 'required'),
			array('id_empresa, evaluacion', 'numerical', 'integerOnly'=>true),
			array('nombre, descripcion', 'length', 'max'=>255),
			array('descripcion, evaluacion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_unidad_negocio, nombre, descripcion, id_empresa, evaluacion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(

			'macroprocesos' => array(self::MANY_MANY, 'Macroproceso', 'unidad_negocio_macroproceso(id_unidad_negocio, id_macroproceso)'),
			'idEmpresa' => array(self::BELONGS_TO, 'Empresa', 'id_empresa'),
			'riesgos' => array(self::MANY_MANY, 'Riesgo', 'riesgo_unidad_negocio(id_unidad_negocio, id_riesgo)'),
			'cuestionarios' => array(self::HAS_MANY, 'Cuestionario', 'id_unidad_negocio'),
		);
	}

	public function pivotModels() {
		return array(
			'macroprocesos' => 'UnidadNegocioMacroproceso',
			'riesgos' => 'RiesgoUnidadNegocio',
		);
	}

	public function attributeLabels() {
		return array(
			'id_unidad_negocio' => Yii::t('app', 'Id Unidad Negocio'),
			'nombre' => Yii::t('app', 'Nombre'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'id_empresa' => null,
			'evaluacion' => Yii::t('app', 'Evaluacion'),
			'macroprocesos' => null,
			'idEmpresa' => null,
			'riesgos' => null,
			'cuestionarios' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_unidad_negocio', $this->id_unidad_negocio);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('id_empresa', $this->id_empresa);
		$criteria->compare('evaluacion', $this->evaluacion);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}