<?php

/**
 * This is the model base class for the table "grupo_riesgo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GrupoRiesgo".
 *
 * Columns in table "grupo_riesgo" available as properties of the model,
 * followed by relations of table "grupo_riesgo" available as properties of the model.
 *
 * @property integer $id_grupo_riesgo
 * @property string $nombre
 * @property string $codigo
 * @property string $descripcion
 *
 * @property Riesgo[] $riesgos
 */
abstract class BaseGrupoRiesgo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'grupo_riesgo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GrupoRiesgo|GrupoRiesgos', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre, codigo', 'required'),
			array('id_grupo_riesgo', 'numerical', 'integerOnly'=>true),
			array('nombre, descripcion', 'length', 'max'=>255),
			array('codigo', 'length', 'max'=>20),
			array('descripcion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_grupo_riesgo, nombre, codigo, descripcion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'riesgos' => array(self::HAS_MANY, 'Riesgo', 'id_grupo_riesgo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_grupo_riesgo' => Yii::t('app', 'Id Grupo Riesgo'),
			'nombre' => Yii::t('app', 'Nombre'),
			'codigo' => Yii::t('app', 'Codigo'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'riesgos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_grupo_riesgo', $this->id_grupo_riesgo);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('codigo', $this->codigo, true);
		$criteria->compare('descripcion', $this->descripcion, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}