<?php

/**
 * This is the model base class for the table "probabilidad_cualitativa".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProbabilidadCualitativa".
 *
 * Columns in table "probabilidad_cualitativa" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_probabilidad_cualitativa
 * @property string $rango_inferior
 * @property string $rango_superior
 * @property string $nombre
 * @property integer $valor
 *
 */
abstract class BaseProbabilidadCualitativa extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'probabilidad_cualitativa';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProbabilidadCualitativa|ProbabilidadCualitativas', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('rango_inferior, rango_superior, nombre, valor', 'required'),
			array('valor', 'numerical', 'integerOnly'=>true),
			array('nombre', 'length', 'max'=>255),
			array('id_probabilidad_cualitativa, rango_inferior, rango_superior, nombre, valor', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_probabilidad_cualitativa' => Yii::t('app', 'Id Probabilidad Cualitativa'),
			'rango_inferior' => Yii::t('app', 'Rango Inferior'),
			'rango_superior' => Yii::t('app', 'Rango Superior'),
			'nombre' => Yii::t('app', 'Nombre'),
			'valor' => Yii::t('app', 'Valor'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_probabilidad_cualitativa', $this->id_probabilidad_cualitativa);
		$criteria->compare('rango_inferior', $this->rango_inferior, true);
		$criteria->compare('rango_superior', $this->rango_superior, true);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('valor', $this->valor);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}