<?php

/**
 * This is the model base class for the table "proceso_riesgo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProcesoRiesgo".
 *
 * Columns in table "proceso_riesgo" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_proceso
 * @property integer $id_riesgo
 *
 */
abstract class BaseProcesoRiesgo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'proceso_riesgo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProcesoRiesgo|ProcesoRiesgos', $n);
	}

	public static function representingColumn() {
		return array(
			'id_proceso',
			'id_riesgo',
		);
	}

	public function rules() {
		return array(
			array('id_proceso, id_riesgo', 'required'),
			array('id_proceso, id_riesgo', 'numerical', 'integerOnly'=>true),
			array('id_proceso, id_riesgo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_proceso' => null,
			'id_riesgo' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_proceso', $this->id_proceso);
		$criteria->compare('id_riesgo', $this->id_riesgo);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}