<?php

/**
 * This is the model base class for the table "unidad_negocio_proceso".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UnidadNegocioProceso".
 *
 * Columns in table "unidad_negocio_proceso" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_unidad_negocio
 * @property integer $id_proceso
 * @property string $nombre_responsable
 *
 */
abstract class BaseUnidadNegocioProceso extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'unidad_negocio_proceso';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UnidadNegocioProceso|UnidadNegocioProcesos', $n);
	}

	public static function representingColumn() {
		return array(
			'id_unidad_negocio',
			'id_proceso',
		);
	}

	public function rules() {
		return array(
			array('id_unidad_negocio, id_proceso, nombre_responsable', 'required'),
			array('id_unidad_negocio, id_proceso', 'numerical', 'integerOnly'=>true),
			array('id_unidad_negocio, id_proceso, nombre_responsable', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_unidad_negocio' => null,
			'id_proceso' => null,
			'nombre_responsable' => Yii::t('app', 'Nombre Responsable'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_unidad_negocio', $this->id_unidad_negocio);
		$criteria->compare('id_proceso', $this->id_proceso);
		$criteria->compare('nombre_responsable', $this->nombre_responsable, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}