<?php

/**
 * This is the model base class for the table "usuario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Usuario".
 *
 * Columns in table "usuario" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_usuario
 * @property string $nombre
 * @property string $apellidos
 * @property string $correo_electronico
 * @property integer $cedula
 * @property integer $telefono
 * @property string $login
 * @property string $password
 * @property string $foto
 * @property integer $estado_cuenta
 *
 */
abstract class BaseUsuario extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'usuario';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Usuario|Usuarios', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre, apellidos, correo_electronico, cedula, telefono, login, password, foto', 'required'),
			array('cedula, estado_cuenta', 'numerical', 'integerOnly'=>true),
			array('nombre, apellidos', 'length', 'max'=>50),
			array('correo_electronico', 'length', 'max'=>30),
			array('login', 'length', 'max'=>20),
			array('password, foto', 'length', 'max'=>255),
			array('estado_cuenta', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_usuario, nombre, apellidos, correo_electronico, cedula, telefono, login, password, foto, estado_cuenta', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_usuario' => Yii::t('app', 'Id Usuario'),
			'nombre' => Yii::t('app', 'Nombre'),
			'apellidos' => Yii::t('app', 'Apellidos'),
			'correo_electronico' => Yii::t('app', 'Correo Electronico'),
			'cedula' => Yii::t('app', 'Cedula'),
			'telefono' => Yii::t('app', 'Telefono'),
			'login' => Yii::t('app', 'Login'),
			'password' => Yii::t('app', 'Password'),
			'foto' => Yii::t('app', 'Foto'),
			'estado_cuenta' => Yii::t('app', 'Estado Cuenta'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_usuario', $this->id_usuario);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('apellidos', $this->apellidos, true);
		$criteria->compare('correo_electronico', $this->correo_electronico, true);
		$criteria->compare('cedula', $this->cedula);
		$criteria->compare('telefono', $this->telefono);
		$criteria->compare('login', $this->login, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('foto', $this->foto, true);
		$criteria->compare('estado_cuenta', $this->estado_cuenta);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}