<?php

/**
 * This is the model base class for the table "unidad_negocio_macroproceso".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UnidadNegocioMacroproceso".
 *
 * Columns in table "unidad_negocio_macroproceso" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_unidad_negocio
 * @property integer $id_macroproceso
 * @property string $nombre_responsable
 *
 */
abstract class BaseUnidadNegocioMacroproceso extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'unidad_negocio_macroproceso';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UnidadNegocioMacroproceso|UnidadNegocioMacroprocesos', $n);
	}

	public static function representingColumn() {
		return array(
			'id_unidad_negocio',
			'id_macroproceso',
		);
	}

	public function rules() {
		return array(
			array('id_unidad_negocio, id_macroproceso, nombre_responsable', 'required'),
			array('id_unidad_negocio, id_macroproceso', 'numerical', 'integerOnly'=>true),
			array('nombre_responsable', 'length', 'max'=>255),
			array('id_unidad_negocio, id_macroproceso, nombre_responsable', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_unidad_negocio' => null,
			'id_macroproceso' => null,
			'nombre_responsable' => Yii::t('app', 'Nombre Responsable'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_unidad_negocio', $this->id_unidad_negocio);
		$criteria->compare('id_macroproceso', $this->id_macroproceso);
		$criteria->compare('nombre_responsable', $this->nombre_responsable, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}